import turtle

turtle.penup()
turtle.goto(0, -150)
turtle.pendown()
turtle.circle(200)
turtle.penup()
turtle.goto(100, 75)
turtle.pendown()
turtle.circle(30)
turtle.penup()
turtle.goto(-100, 75)
turtle.pendown()
turtle.circle(30)
turtle.penup()
turtle.goto(-90, -50)
turtle.pendown()
turtle.forward(180)
turtle.goto(0, -80)
turtle.goto(-90, -50)
